CREATE TABLE `live_analysis_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`liveSessionId` int NOT NULL,
	`userId` int NOT NULL,
	`windowIndex` int NOT NULL,
	`windowStartSeconds` int NOT NULL,
	`windowEndSeconds` int NOT NULL,
	`visibleAction` text,
	`formation` varchar(96),
	`personnel` varchar(96),
	`defensiveLook` varchar(128),
	`playCall` varchar(160),
	`predictionSummary` text,
	`nextPlayProbabilities` json,
	`tendencyShift` text,
	`counterCall` text,
	`riskLevel` enum('low','moderate','high','critical') NOT NULL DEFAULT 'low',
	`alerts` json,
	`evidence` json,
	`confidence` int NOT NULL DEFAULT 0,
	`inputFrameCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `live_analysis_events_id` PRIMARY KEY(`id`),
	CONSTRAINT `live_event_session_window_unique` UNIQUE(`liveSessionId`,`windowIndex`)
);
--> statement-breakpoint
CREATE TABLE `live_game_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(160) NOT NULL,
	`opponentName` varchar(255) NOT NULL,
	`sourceType` enum('upload','camera') NOT NULL,
	`videoFileKey` text,
	`videoUrl` text,
	`status` enum('setup','ready','live','paused','complete','failed') NOT NULL DEFAULT 'setup',
	`analysisIntervalSeconds` int NOT NULL DEFAULT 15,
	`currentVideoSecond` int NOT NULL DEFAULT 0,
	`situation` json,
	`latestSummary` text,
	`errorMessage` text,
	`startedAt` timestamp,
	`endedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `live_game_sessions_id` PRIMARY KEY(`id`)
);
