CREATE TABLE `play_reconstructions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`sourceKind` varchar(32) NOT NULL,
	`sourceKey` varchar(191) NOT NULL,
	`gameSessionId` int,
	`liveSessionId` int,
	`liveEventId` int,
	`sourceType` varchar(32) NOT NULL,
	`sourceTitle` varchar(255) NOT NULL,
	`sourceDescription` text,
	`sourceStartSeconds` int NOT NULL DEFAULT 0,
	`sourceEndSeconds` int NOT NULL DEFAULT 12,
	`youtubeVideoId` varchar(64),
	`videoUrl` text,
	`title` varchar(255) NOT NULL,
	`formation` varchar(96) NOT NULL DEFAULT 'Unknown Formation',
	`playType` varchar(32) NOT NULL DEFAULT 'unknown',
	`target` varchar(96),
	`defenseScheme` varchar(96) NOT NULL DEFAULT '4-3',
	`players` json NOT NULL,
	`ballPath` json NOT NULL,
	`markers` json NOT NULL,
	`coachingNotes` text,
	`confidence` int NOT NULL DEFAULT 0,
	`status` enum('draft','reviewed') NOT NULL DEFAULT 'draft',
	`coachVerified` int NOT NULL DEFAULT 0,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `play_reconstructions_id` PRIMARY KEY(`id`),
	CONSTRAINT `twin_owner_source_unique` UNIQUE(`userId`,`sourceKey`)
);
